### ISSUE TITLE
Update xml package to 6.0.0

### ISSUE THREAD

**Issue by robert-ancell** [canonical/dbus_client.dart#341]
Tests currently fail due to [xml no longer correctly handling invalid XML documents](https://github.com/renggli/dart-xml/issues/143).

**Comment by MagnusJohansson** [comment]
Yes please, upgrade from xml 5.0.0 to xml 6.0.0.
I have numerous packages that now depends on xml 6.0.0, and that makes dbus incompatible.

**Comment by robert-ancell** [comment]
I was waiting on upstream to make a 6.0.2 release with the fix, I'll ask them to do that ASAP.

**Comment by robert-ancell** [comment]
And if that's not possible I'll look at adding a workaround to dbus.dart so we can use the current version.

**Comment by red-game-dev** [comment]
v6.1.0 was released as well

[XML 6.1.0](https://pub.dev/packages/xml/versions/6.1.0)

**Comment by MattCCC** [comment]
hi guys, firstly thank you for the great plugin. Any news on this one? It's quite a blocker on one of my projects 😞
