### ISSUE TITLE
Rename file at `bin/dart_dbus.dart` to `bin/dbus.dart` for ease of use. 

### ISSUE THREAD

**Issue by markvideon** [canonical/dbus_client.dart#358]
If I add some package intended for use as a CLI to a for a Flutter application's dependencies, I can run that using `flutter pub run [package_name] [arg1] ... [argN]`.

I'd like to suggest renaming this package's file in /bin, and an update to the readme highlighting that it is possible to consume the CLI in the above way for anyone with the Flutter SDK installed.

**Comment by aadarshadhakalg** [comment]
But then if I want to install it globally, will it be possible?

**Comment by jonasfj** [comment]
>  But then if I want to install it globally, will it be possible?

Yes!

@aadarshadhakalg 
You'll just need an `executables: {'dart-dbus': 'dbus'}` in `pubspec.yaml`.


But also, don't globally activate it. You'll want the version of `package:dbus` used for codegen to be the same version as you're using to run your code.

For more details see https://github.com/canonical/dbus.dart/issues/362

**Comment by markvideon** [comment]
Closing based on comments in #362
