### ISSUE TITLE
Authentication Example

### ISSUE THREAD

**Issue by wstrange** [canonical/dbus_client.dart#373]
Disclaimer: I'm a DBus newbie, so this issue might be a case of me not understanding how the protocol works.

The use case: A Dart (or Flutter) application, launched as a non root user, but wants to issue a DBus command that requires root privileges. Is there a way to programmatically `su` the DBus session (assume we prompt the user for the password).

An example would be really helpful.

**Comment by robert-ancell** [comment]
DBus is an IPC mechanism, so the each side of the communication may be different users. When a service is running as root, it normally uses [polkit](https://www.freedesktop.org/software/polkit/docs/latest/polkit.8.html) to authorize the client that is making the request. The client program doesn't need to do anything special. I would expect in most cases a Dart application is running as the user and contacting a root service, so no special code is required.

**Comment by wstrange** [comment]
I'll admit I don't quite grok that explanation..

The example I have in mind is a user restarting a Systemd service.   From the cli, they would use `sudo` and provide their password.

How would a Flutter application, launched as a non root user, perform the equivalent.  

I gather you could launch the entire Flutter app using `sudo`, but I want to progressively authenticate where required.

**Comment by robert-ancell** [comment]
Your Flutter application can just make a standard D-Bus call to systemd and as long as allowInteractiveAuthorization is set to true in `DBusClient.callMethod` this will work (a polkit prompt will be shown to the user when the request is made).
