### ISSUE TITLE
DBusGetPropertyResponse wraps everything in DBusVariant

### ISSUE THREAD

**Issue by mennovanhout** [canonical/dbus_client.dart#374]
Hi there,

I'am wondering if this is a bug or a desired solution.
Due the fact documentation says we need to overwrite objects created.

```
class MyAdvertisement extends OrgBluezLEAdvertisement1 {
  MyAdvertisement({super.path});

  @override
  Future<DBusGetPropertyResponse> getType() async {
    return DBusGetPropertyResponse(const DBusString('peripheral'));
  }
```

I've found out the returned value becomes DBusVariant instead of DBusString and thus it returns the error:
```src/advertising.c:parse_advertisement() Error parsing Type property```

It's actually caused by the constructer of DBusGetPropertyResponse

```
class DBusGetPropertyResponse extends DBusMethodSuccessResponse {
  DBusGetPropertyResponse(DBusValue value) : super([DBusVariant(value)]);

  @override
  String toString() => '$runtimeType($values[0])';
}
```

As you can see super wraps it into an DBusVariant which doesn't make it a string anymore.
Adding another constructor that doesn't have this behaviour solves it.

```class DBusGetPropertyResponse extends DBusMethodSuccessResponse {
  DBusGetPropertyResponse(DBusValue value) : super([DBusVariant(value)]);

  DBusGetPropertyResponse.direct(DBusValue value) : super([value]);

  @override
  String toString() => '$runtimeType($values[0])';
}
```

The only question left is why? what is the purpose of wrapping it in DBusVariant?

**Comment by robert-ancell** [comment]
This class is implementing the `org.freedesktop.DBus.Properties` interface - https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces-properties, specifically:

```
org.freedesktop.DBus.Properties.Get (in STRING interface_name, in STRING property_name, out VARIANT value);
```

So the property has to be returned as a variant which the `DBusGetPropertyResponse` does for you.

**Comment by mennovanhout** [comment]
> has to be returned as a variant which the `DBusGetPropertyResponse`

But that doesn't comply with the class being generated from the XML interface.
The XML interface clearly expects a string. So the result of this code is that DBus rejects my package as variant is not accapted as string. And it doesn't comply with the XML interface.

**Comment by robert-ancell** [comment]
Can you show more of the code you are using? Where is the code for `src/advertising.c`?
